Bolt: stack Class Reference
stack Class Reference
Public Member Functions
__construct ($class=false)
setTotal ($t)
setLimit ($l)
setOffset ($o)
setMeta ($o)
__call ($name, $args)
__get ($name)
__set ($name, $value)
push ($item, $key=false)
add ($item)
item ($idx=0)
import ($items)
reduce ($cb)
map ($cb)
filter ($cb)
sort ($cb, $sort=false)
each ($cb)
asArray ()
Detailed Description
Definition at line 5 of file stack.php.
Constructor & Destructor Documentation
__construct ($ class = false)
Definition at line 18 of file stack.php.
Member Function Documentation
__call ($ name, $ args)
Definition at line 43 of file stack.php.
__get ($ name)
Definition at line 47 of file stack.php.
__set ($ name, $ value)
Definition at line 51 of file stack.php.
add ($ item)
Definition at line 84 of file stack.php.
References push().
asArray ()
Definition at line 256 of file stack.php.
each ($ cb)
Definition at line 244 of file stack.php.
filter ($ cb)
Definition at line 200 of file stack.php.
import ($ items)
Definition at line 120 of file stack.php.
References push().
item ($ idx = 0)
Definition at line 89 of file stack.php.
Referenced by sort().
map ($ cb)
Definition at line 168 of file stack.php.
push ($ item, $ key = false)
Definition at line 56 of file stack.php.
Referenced by add(), and import().
reduce ($ cb)
Definition at line 127 of file stack.php.
setLimit ($ l)
Definition at line 27 of file stack.php.
setMeta ($ o)
Definition at line 37 of file stack.php.
setOffset ($ o)
Definition at line 32 of file stack.php.
setTotal ($ t)
Definition at line 22 of file stack.php.
sort ($ cb, $ sort = false)
Definition at line 214 of file stack.php.
References item().
The documentation for this class was generated from the following file:
stack.php