Bolt: item Class Reference
item Class Reference
dao item
Public Member Functions
loaded ()
is the object loaded
__construct ($data=array())
construct a DAO
__get ($name)
MAGIC get a property from data array.
__set ($name, $val)
MAGIC set a property from data array.
__toString ()
MAGIC return object as json array.
__call ($name, $args)
MAGIC call a function.
set ($data)
default set action
getDataValue ($name, $object=false)
normalize ()
normalize the data for insert
asArray ($adjunct=false)
print object as an array
getItemData ()
get data array
rewind ()
reset pointer to first item in set
current ()
get the current item pointer
key ()
key value of current pointer item
next ()
go to next item in the set
valid ()
check if the current value is valid
count ()
item ($idx=0)
offsetSet ($offset, $value)
offsetExists ($offset)
offsetUnset ($offset)
offsetGet ($offset)
Public Attributes
$_guid
$_adjunct = array()
Protected Member Functions
getStruct ()
return the object construct
Protected Attributes
$_useAddedTimestamp = false
$_useModifiedTimestamp = false
Detailed Description
dao item
Definition at line 9 of file item.php.
Constructor & Destructor Documentation
__construct ($ data = array())
construct a DAO
Definition at line 46 of file item.php.
References count(), and getStruct().
Member Function Documentation
__call ($ name, $ args)
MAGIC call a function.
Returns:
mixed
Definition at line 355 of file item.php.
__get ($ name)
MAGIC get a property from data array.
Parameters:
name name of the property to get from the data array
Returns:
value if property exists. false if property does not exist
Definition at line 79 of file item.php.
References dao, and getStruct().
__set ($ name, $ val)
MAGIC set a property from data array.
Parameters:
name name of the property to set in the data array
val value to set property to
Returns:
null
Definition at line 226 of file item.php.
References p().
__toString ()
MAGIC return object as json array.
Returns:
data array as json string
Definition at line 346 of file item.php.
asArray ($ adjunct = false)
print object as an array
Parameters:
key return only single key as array
Returns:
data object value as array
Definition at line 677 of file item.php.
count ()
Definition at line 817 of file item.php.
Referenced by __construct().
current ()
get the current item pointer
Returns:
value of current pointer item
Definition at line 779 of file item.php.
getDataValue ($ name, $ object = false)
Definition at line 435 of file item.php.
getItemData ()
get data array
Returns:
data aray;
Definition at line 760 of file item.php.
getStruct () [protected]
return the object construct
Returns:
array with object construct
Definition at line 32 of file item.php.
Referenced by __construct(), and __get().
item ($ idx = 0)
Definition at line 822 of file item.php.
key ()
key value of current pointer item
Returns:
value of pointer item
Definition at line 790 of file item.php.
loaded ()
is the object loaded
Returns:
bool
Definition at line 41 of file item.php.
next ()
go to next item in the set
Returns:
value of next item in set
Definition at line 801 of file item.php.
normalize ()
normalize the data for insert
Returns:
array
Definition at line 445 of file item.php.
offsetExists ($ offset)
Definition at line 854 of file item.php.
offsetGet ($ offset)
Definition at line 860 of file item.php.
offsetSet ($ offset, $ value)
Definition at line 851 of file item.php.
offsetUnset ($ offset)
Definition at line 857 of file item.php.
rewind ()
reset pointer to first item in set
Returns:
void
Definition at line 769 of file item.php.
set ($ data)
default set action
Parameters:
$data array of data to set
Returns:
void
Definition at line 423 of file item.php.
valid ()
check if the current value is valid
Returns:
bool if current value is valid
Definition at line 812 of file item.php.
Member Data Documentation
$_adjunct = array()
Definition at line 24 of file item.php.
$_guid
Definition at line 12 of file item.php.
$_useAddedTimestamp = false [protected]
Definition at line 22 of file item.php.
$_useModifiedTimestamp = false [protected]
Definition at line 23 of file item.php.
The documentation for this class was generated from the following file:
item.php