Bolt: mongoi Class Reference
mongoi Class Reference
Public Member Functions
__construct ($config)
__call ($name, $args)
__get ($name)
setDb ($name)
getDb ()
getHandle ()
getGridFS ($db='fs', $prefix="fs")
query ($collection, $query, $args=array())
count ($collection, $query=array(), $args=array())
row ($collection, $query, $args=array())
insert ($collection, $data, $safe=false, $args=array())
update ($collection, $query, $data, $opts=array(), $args=array())
delete ($collection, $query, $opts=array(), $args=array())
Detailed Description
Definition at line 30 of file source/mongo.php.
Constructor & Destructor Documentation
__construct ($ config)
Definition at line 39 of file source/mongo.php.
Member Function Documentation
__call ($ name, $ args)
Definition at line 71 of file source/mongo.php.
References getHandle().
__get ($ name)
Definition at line 75 of file source/mongo.php.
References getHandle().
count ($ collection, $ query = array(), $ args = array())
Definition at line 172 of file source/mongo.php.
delete ($ collection, $ query, $ opts = array(), $ args = array())
Definition at line 253 of file source/mongo.php.
getDb ()
Definition at line 87 of file source/mongo.php.
getGridFS ($ db = 'fs', $ prefix = "fs")
Definition at line 96 of file source/mongo.php.
getHandle ()
Definition at line 91 of file source/mongo.php.
Referenced by __call(), and __get().
insert ($ collection, $ data, $ safe = false, $ args = array())
Definition at line 207 of file source/mongo.php.
query ($ collection, $ query, $ args = array())
Definition at line 109 of file source/mongo.php.
row ($ collection, $ query, $ args = array())
Definition at line 191 of file source/mongo.php.
setDb ($ name)
Definition at line 79 of file source/mongo.php.
update ($ collection, $ query, $ data, $ opts = array(), $ args = array())
Definition at line 231 of file source/mongo.php.
The documentation for this class was generated from the following file:
source/mongo.php