Bolt: bolt.php File Reference
bolt.php File Reference
Classes
class b
static bolt wrapper instance
class bolt
wrapper for single bolt instance
Functions
p ($key, $default=false, $array=false, $filter=FILTER_SANITIZE_STRING)
global paramater check
p_raw ($key, $default=false, $array=false)
global raw paramater check
pp ($pos, $default=false, $filter=false)
global path paramater check p
Variables
$path = explode("/",$_SERVER['SCRIPT_FILENAME'])
$uri = explode('/',$_SERVER['SCRIPT_NAME'])
Function Documentation
p ($ key, $ default = false, $ array = false, $ filter = FILTER_SANITIZE_STRING)
global paramater check
p
Parameters:
$key key name
$default default value if key != exist [Default: false]
$array array to look in [Default: $_REQUEST]
$filter string to filter on the return
Returns:
mixed paramater value
Definition at line 290 of file bolt.php.
Referenced by memcachei::__construct(), item::__set(), account::create(), route::execute(), cookie::get(), view::getParam(), session::login(), p_raw(), route::register(), render::render(), helpers::sendEmail(), cookie::set(), and session::verify().
p_raw ($ key, $ default = false, $ array = false)
global raw paramater check
p_raw
Parameters:
$key key name
$default default value if key != exist [Default: false]
$array array to look in [Default: $_REQUEST]
Returns:
mixed paratamer value
See also:
p
Definition at line 371 of file bolt.php.
References p().
pp ($ pos, $ default = false, $ filter = false)
global path paramater check p
Parameters:
$pos index position of key
$default default value if key != exist [Default: false]
$array array to look in [Default: $_REQUEST]
$filter string to filter on the return
Returns:
mixed path paramter
Definition at line 384 of file bolt.php.
References $path.
Variable Documentation
$path = explode("/",$_SERVER['SCRIPT_FILENAME'])
Definition at line 410 of file bolt.php.
Referenced by route::execute(), route::match(), pp(), route::register(), CdnImages::sign(), and route::url().
$uri = explode('/',$_SERVER['SCRIPT_NAME'])
Definition at line 413 of file bolt.php.
Referenced by S3Request::__construct(), S3::copyObject(), S3::deleteObject(), S3::getAccessControlPolicy(), S3::getAuthenticatedURL(), S3::getObject(), S3::getObjectInfo(), CdnImages::post(), S3::putObject(), S3::putObjectFile(), S3::putObjectString(), CdnImages::request(), S3::setAccessControlPolicy(), and route::url().