Bolt: helpers Class Reference
helpers Class Reference
Public Member Functions
md5 ($str)
location ()
sendEmail ($args)
Static Public Member Functions
static crypt ($str, $salt=false)
encrypt a password
static encrypt ($str, $salt)
encrypt using mcrypt
static deencrypt ($str, $salt)
deencrypt using mcrypt
static mcrypt ($str, $salt=false, $what=MCRYPT_DECRYPT)
mcrypt
static addUrlParams ($url, $params=array())
add url params to a url
static randString ($len=30)
generate a random string
static randomString ($len=30)
static slug ($str)
static uuid ($parts=5, $prefix=false)
static utctime ()
static convertTimestamp ($ts, $to, $from='UTC')
static plural ($str, $count, $multi=false)
static possesive ($str)
static niceDate ($ts)
static ago ($tm, $short=false)
static left ($theTime, $level="days+hours+min+sec")
static short ($str, $len=200, $onwords=true)
static br2nl ($string)
static show_404 ($page=b404)
static convertBase ($str, $to=36, $from=10)
static mergeArray ($a1, $a2)
Detailed Description
Definition at line 13 of file helpers.php.
Member Function Documentation
static addUrlParams ($ url, $ params = array()) [static]
add url params to a url
Parameters:
$url base url
$params array of params to add
Returns:
string url with additional params
Definition at line 92 of file helpers.php.
Referenced by location().
static ago ($ tm, $ short = false) [static]
Definition at line 275 of file helpers.php.
References utctime().
static br2nl ($ string) [static]
Definition at line 385 of file helpers.php.
static convertBase ($ str, $ to = 36, $ from = 10) [static]
Definition at line 404 of file helpers.php.
static convertTimestamp ($ ts, $ to, $ from = 'UTC') [static]
Definition at line 225 of file helpers.php.
static crypt ($ str, $ salt = false) [static]
encrypt a password
Definition at line 19 of file helpers.php.
static deencrypt ($ str, $ salt) [static]
deencrypt using mcrypt
Definition at line 34 of file helpers.php.
References mcrypt().
static encrypt ($ str, $ salt) [static]
encrypt using mcrypt
Definition at line 27 of file helpers.php.
References mcrypt().
static left ($ theTime, $ level = "days+hours+min+sec") [static]
Definition at line 317 of file helpers.php.
location ()
Definition at line 167 of file helpers.php.
References addUrlParams().
static mcrypt ($ str, $ salt = false, $ what = MCRYPT_DECRYPT) [static]
mcrypt
Definition at line 41 of file helpers.php.
References b::_(), and md5().
Referenced by deencrypt(), and encrypt().
md5 ($ str)
Definition at line 163 of file helpers.php.
Referenced by mcrypt().
static mergeArray ($ a1, $ a2) [static]
Definition at line 457 of file helpers.php.
static niceDate ($ ts) [static]
Definition at line 259 of file helpers.php.
References b::SecondsInYear, and utctime().
static plural ($ str, $ count, $ multi = false) [static]
Definition at line 241 of file helpers.php.
static possesive ($ str) [static]
Definition at line 254 of file helpers.php.
static randomString ($ len = 30) [static]
Definition at line 158 of file helpers.php.
References randString().
static randString ($ len = 30) [static]
generate a random string
Parameters:
$len lenth of string
Returns:
random string
Definition at line 135 of file helpers.php.
Referenced by randomString().
sendEmail ($ args)
Definition at line 408 of file helpers.php.
References p().
static short ($ str, $ len = 200, $ onwords = true) [static]
Definition at line 361 of file helpers.php.
static show_404 ($ page = b404) [static]
Definition at line 391 of file helpers.php.
static slug ($ str) [static]
Definition at line 184 of file helpers.php.
static utctime () [static]
Definition at line 215 of file helpers.php.
Referenced by ago(), and niceDate().
static uuid ($ parts = 5, $ prefix = false) [static]
Definition at line 201 of file helpers.php.
The documentation for this class was generated from the following file:
helpers.php