#!/usr/bin/env php
<?php

$opts = getopt("hcd:f:");

if (isset($opts['h'])) {
    exit("\nusage: ./run -c -d <dir> -h\n -c   run coverage test\n -d   directory/files to limit test\n\n");
}

if (trim(`which phpunit`) === "") {
    exit("Unable to find PHPUnit.\n".
         "We need PHPUnit to run our tests!\n\n".
         "You can install from PEAR:\n".
         " pear config-set auto_discover 1\n".
         " pear install pear.phpunit.de/phpunit\n\n");
}



$root = __DIR__;
$in = realpath($root."/".(isset($opts["d"]) ? $opts["d"] : "./"));

$cmd = 'phpunit --bootstrap="'.$root.'/bootstrap.php" ';

// report
if (isset($opts['c'])) {
    $cmd .= ' --coverage-html '.$root.'/coverage';
}
if (isset($opts['f'])) {
    $cmd .= ' --filter '.$opts['f'];
}

$cmd .= ' '.$in;

echo `$cmd`;
