#!/usr/bin/env php
<?php

if (`which phpunit` === trim("")) {
    exit("Unable to find PHPUnit.\n".
         "We need PHPUnit to run our tests!\n\n".
         "You can install from PEAR:\n".
         " pear config-set auto_discover 1\n".
         " pear install pear.phpunit.de/phpunit\n\n");
}

$root = __DIR__;
$in = realpath($root."/".(isset($argv[1]) ? $argv[1] : "./"));

echo `phpunit --bootstrap="$root/bootstrap.php" $in`;
