Bolt: webservice Class Reference
webservice Class Reference
Public Member Functions
__construct ()
request ()
ws ()
__construct ($cfg=array())
getLastResponse ()
config ($key, $val=false)
__get ($name)
__set ($name, $value=false)
request ()
getCurl ()
getOauth ()
Protected Member Functions
curlRequest ($url, $params=array(), $method="GET", $headers=array(), $useIniFilePost=false)
oauthRequest ($url, $params=array(), $method="GET", $headers=array())
Protected Attributes
$wsConfig = false
Detailed Description
Definition at line 6 of file dao/source/webservice.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 13 of file dao/source/webservice.php.
__construct ($ cfg = array())
Definition at line 28 of file source/webservice.php.
Member Function Documentation
__get ($ name)
Definition at line 51 of file source/webservice.php.
__set ($ name, $ value = false)
Definition at line 56 of file source/webservice.php.
Referenced by config().
config ($ key, $ val = false)
Definition at line 36 of file source/webservice.php.
References __set().
curlRequest ($ url, $ params = array(), $ method = "GET", $ headers = array(), $ useIniFilePost = false) [protected]
Definition at line 91 of file source/webservice.php.
References getCurl().
getCurl ()
Definition at line 84 of file source/webservice.php.
Referenced by curlRequest().
getLastResponse ()
Definition at line 32 of file source/webservice.php.
getOauth ()
Definition at line 87 of file source/webservice.php.
oauthRequest ($ url, $ params = array(), $ method = "GET", $ headers = array()) [protected]
Definition at line 198 of file source/webservice.php.
request ()
Definition at line 61 of file source/webservice.php.
request ()
Definition at line 24 of file dao/source/webservice.php.
ws ()
Definition at line 29 of file dao/source/webservice.php.
Member Data Documentation
$wsConfig = false [protected]
Definition at line 9 of file dao/source/webservice.php.
The documentation for this class was generated from the following files:
dao/source/webservice.php
source/webservice.php