Bolt: view Class Reference
view Class Reference
Public Member Functions
__construct ($params=array(), $method=false)
__call ($name, $args)
getWrap ()
getParam ($name, $default=false)
setParam ($name, $value=false)
__get ($name)
__set ($name, $value)
render ($tmpl=false, $args=array())
execute ($params=array(), $accept=false)
Protected Member Functions
template ($tmpl)
Protected Attributes
$accept = array('*/*')
Detailed Description
Definition at line 6 of file view.php.
Constructor & Destructor Documentation
__construct ($ params = array(), $ method = false)
Definition at line 24 of file view.php.
Member Function Documentation
__call ($ name, $ args)
Definition at line 33 of file view.php.
__get ($ name)
Definition at line 111 of file view.php.
References getParam().
__set ($ name, $ value)
Definition at line 116 of file view.php.
References setParam().
execute ($ params = array(), $ accept = false)
Definition at line 144 of file view.php.
References $accept.
getParam ($ name, $ default = false)
Definition at line 96 of file view.php.
References p().
Referenced by __get().
getWrap ()
Definition at line 86 of file view.php.
render ($ tmpl = false, $ args = array())
Definition at line 121 of file view.php.
References render.
setParam ($ name, $ value = false)
Definition at line 106 of file view.php.
Referenced by __set().
template ($ tmpl) [protected]
Definition at line 91 of file view.php.
Member Data Documentation
$accept = array('*/*') [protected]
Definition at line 21 of file view.php.
Referenced by execute().
The documentation for this class was generated from the following file:
view.php