Bolt: mongo Class Reference
mongo Class Reference
Public Member Functions
getCacheHandler ()
get ()
row ($field, $val=array())
query ($query, $args=array())
save ()
delete ()
getGridFS ()
__construct ($args=array())
__call ($name, $args)
Protected Attributes
$table = false
$cache = array('enable' => true, 'handler' => 'memcache', 'ttl' => 0)
Detailed Description
Definition at line 6 of file dao/source/mongo.php.
Constructor & Destructor Documentation
__construct ($ args = array())
Definition at line 18 of file source/mongo.php.
References source.
Member Function Documentation
__call ($ name, $ args)
Definition at line 23 of file source/mongo.php.
delete ()
Definition at line 141 of file dao/source/mongo.php.
get ()
Definition at line 24 of file dao/source/mongo.php.
getCacheHandler ()
Definition at line 14 of file dao/source/mongo.php.
References cache.
Referenced by row(), and save().
getGridFS ()
Definition at line 145 of file dao/source/mongo.php.
query ($ query, $ args = array())
Definition at line 77 of file dao/source/mongo.php.
References dao.
row ($ field, $ val = array())
Definition at line 39 of file dao/source/mongo.php.
References getCacheHandler().
save ()
Definition at line 104 of file dao/source/mongo.php.
References getCacheHandler().
Member Data Documentation
$cache = array('enable' => true, 'handler' => 'memcache', 'ttl' => 0) [protected]
Definition at line 12 of file dao/source/mongo.php.
$table = false [protected]
Definition at line 9 of file dao/source/mongo.php.
The documentation for this class was generated from the following files:
dao/source/mongo.php
source/mongo.php