Bolt: CdnImages Class Reference
CdnImages Class Reference
Static Public Member Functions
static setup ($args)
set internal values
static sign ($path, $cmds=array())
sign an image url
static signString ($str)
sign an string that may contain img tags
static getHost ()
get the hostname to use
static post ($src, $dest, $args=array())
post an image to the cdn
static get ($src)
get an image from the cdn
static request ($uri, $params=array(), $method="GET", $headers=array())
get an image from the cdn
Public Attributes
const VERSION = "1.0"
Static Public Attributes
static $key
static $secret
static $domain
static $cname
static $cmds = false
static $api = "api.cdnimag.es"
static $apiVersion = "v1"
Detailed Description
Definition at line 17 of file CdnImages.php.
Member Function Documentation
static get ($ src) [static]
get an image from the cdn
Returns:
string with hostname
Definition at line 246 of file CdnImages.php.
static getHost () [static]
get the hostname to use
Returns:
string with hostname
Definition at line 179 of file CdnImages.php.
static post ($ src, $ dest, $ args = array()) [static]
post an image to the cdn
Parameters:
mixed image source. file name or handle
string destination path
Returns:
string with hostname
Definition at line 197 of file CdnImages.php.
References $uri, Exception, request(), and sign().
static request ($ uri, $ params = array(), $ method = "GET", $ headers = array()) [static]
get an image from the cdn
Returns:
string with hostname
Definition at line 257 of file CdnImages.php.
References $uri, and Exception.
Referenced by post().
static setup ($ args) [static]
set internal values
Parameters:
string domain name
string api key
string api secret
Returns:
void
Definition at line 40 of file CdnImages.php.
static sign ($ path, $ cmds = array()) [static]
sign an image url
Parameters:
string path to image
hash image commands
Returns:
string signed url
Definition at line 64 of file CdnImages.php.
References $cmds, and $path.
Referenced by post().
static signString ($ str) [static]
sign an string that may contain img tags
Parameters:
string path to image
Returns:
string signed url
Definition at line 106 of file CdnImages.php.
Member Data Documentation
$api = "api.cdnimag.es" [static]
Definition at line 23 of file CdnImages.php.
$apiVersion = "v1" [static]
Definition at line 26 of file CdnImages.php.
$cmds = false [static]
Definition at line 20 of file CdnImages.php.
Referenced by sign().
$cname [static]
Definition at line 20 of file CdnImages.php.
$domain [static]
Definition at line 20 of file CdnImages.php.
$key [static]
Definition at line 20 of file CdnImages.php.
$secret [static]
Definition at line 20 of file CdnImages.php.
const VERSION = "1.0"
Definition at line 29 of file CdnImages.php.
The documentation for this class was generated from the following file:
CdnImages.php