Bolt: render Class Reference
render Class Reference
Public Member Functions
_default ($args=array())
__get ($key)
__set ($key, $value)
get ($key)
set ()
register ($name, $class, $type='factory')
moduleExists ($name)
template ($tmpl, $args=array(), $view=false)
string ($str, $vars=array(), $view=false)
render ($view, $args=array())
Static Public Attributes
static $TYPE = 'singleton'
Detailed Description
Definition at line 13 of file render.php.
Member Function Documentation
__get ($ key)
Definition at line 60 of file render.php.
__set ($ key, $ value)
Definition at line 65 of file render.php.
_default ($ args = array())
Definition at line 25 of file render.php.
References string().
get ($ key)
Definition at line 69 of file render.php.
moduleExists ($ name)
Definition at line 99 of file render.php.
register ($ name, $ class, $ type = 'factory')
Definition at line 89 of file render.php.
render ($ view, $ args = array())
Definition at line 328 of file render.php.
References plugin::call(), plugin::getPlugins(), and p().
set ()
Definition at line 74 of file render.php.
string ($ str, $ vars = array(), $ view = false)
Definition at line 154 of file render.php.
References Exception.
Referenced by _default(), and template().
template ($ tmpl, $ args = array(), $ view = false)
Definition at line 103 of file render.php.
References string().
Member Data Documentation
$TYPE = 'singleton' [static]
Definition at line 16 of file render.php.
The documentation for this class was generated from the following file:
render.php