Bolt: route Class Reference
route Class Reference
Public Member Functions
_default ()
getRoutes ()
register ($paths, $class=false, $name=false, $args=array())
match ($path=false)
execute ($args=array())
url ($name, $data=array(), $params=array(), $uri=false)
Detailed Description
Definition at line 17 of file route.php.
Member Function Documentation
_default ()
Definition at line 24 of file route.php.
execute ($ args = array())
Definition at line 162 of file route.php.
References $path, match(), p(), and render.
getRoutes ()
Definition at line 34 of file route.php.
match ($ path = false)
Definition at line 101 of file route.php.
References $path, and b::_().
Referenced by execute().
register ($ paths, $ class = false, $ name = false, $ args = array())
Definition at line 39 of file route.php.
References $path, and p().
url ($ name, $ data = array(), $ params = array(), $ uri = false)
Definition at line 191 of file route.php.
References $path, and $uri.
The documentation for this class was generated from the following file:
route.php