Bolt: session Class Reference
session Class Reference
Public Member Functions
start ($id=false)
regenerate ($id=false)
__destruct ()
getSid ()
sid ()
__get ($key)
__set ($key, $value)
set ($data)
__call ($name, $args)
load ()
save ()
delete ()
verify ()
login ($args)
logout ()
Public Attributes
$_id = false
$_changed = false
Detailed Description
Definition at line 19 of file session.php.
Constructor & Destructor Documentation
__destruct ()
Definition at line 79 of file session.php.
References save().
Member Function Documentation
__call ($ name, $ args)
Definition at line 111 of file session.php.
__get ($ key)
Definition at line 93 of file session.php.
__set ($ key, $ value)
Definition at line 99 of file session.php.
Referenced by set().
delete ()
Definition at line 156 of file session.php.
getSid ()
Definition at line 83 of file session.php.
References sid().
load ()
Definition at line 116 of file session.php.
References dao.
Referenced by regenerate(), and start().
login ($ args)
Definition at line 181 of file session.php.
References b::_(), and p().
logout ()
Definition at line 244 of file session.php.
regenerate ($ id = false)
Definition at line 71 of file session.php.
References load().
Referenced by start().
save ()
Definition at line 137 of file session.php.
References sid().
Referenced by __destruct().
set ($ data)
Definition at line 104 of file session.php.
References __set().
sid ()
Definition at line 87 of file session.php.
Referenced by getSid(), and save().
start ($ id = false)
Definition at line 32 of file session.php.
References load(), and regenerate().
Referenced by verify().
verify ()
Definition at line 162 of file session.php.
References p(), and start().
Member Data Documentation
$_changed = false
Definition at line 28 of file session.php.
$_id = false
Definition at line 27 of file session.php.
The documentation for this class was generated from the following file:
session.php