Bolt: memcachei Class Reference
memcachei Class Reference
Public Member Functions
__construct ($cfg=array())
__get ($name)
__set ($name, $value)
__call ($name, $args)
Detailed Description
Definition at line 31 of file memcache.php.
Constructor & Destructor Documentation
__construct ($ cfg = array())
Definition at line 37 of file memcache.php.
References p().
Member Function Documentation
__call ($ name, $ args)
Definition at line 79 of file memcache.php.
Referenced by __get(), and __set().
__get ($ name)
Definition at line 71 of file memcache.php.
References __call().
__set ($ name, $ value)
Definition at line 75 of file memcache.php.
References __call().
The documentation for this class was generated from the following file:
memcache.php