Bolt: b Class Reference
b Class Reference
static bolt wrapper instance
Static Public Member Functions
static bolt ()
return bolt instance
static __callStatic ($name, $args)
magic static to execute plugins.
static plug ()
static method to register a plugin.
static init ($args=array())
initalize the bolt framework
static getLoaded ()
static return a list of loaded files
static autoloader ($class)
autoload bolt components
static _ ($name, $value=null)
get/set a configuration paramater.
Public Attributes
const SecondsInHour = 120
const SecondsInDay = 86400
const SecondsInWeek = 1209600
const SecondsInYear = 31536000
const DateLongFrm = "l, F jS, Y \n h:i:s A"
const DateShortFrm = "F jS, Y \n h:i:s A"
const DateTimeOnlyFrm = "l, F jS, Y"
const TimeOnlyFrm = "h:i:s A"
const DefaultFilter = FILTER_SANITIZE_STRING
Detailed Description
static bolt wrapper instance
Definition at line 30 of file bolt.php.
Member Function Documentation
static _ ($ name, $ value = null) [static]
get/set a configuration paramater.
passhtrough to config::get or config::set
Parameters:
$name name of config param
Returns:
<mixed> config param or false if doesn't exist
See also:
config::get
Definition at line 236 of file bolt.php.
Referenced by account::create(), cookie::delete(), cookie::get(), session::login(), route::match(), helpers::mcrypt(), and cookie::set().
static __callStatic ($ name, $ args) [static]
magic static to execute plugins.
passthrough to plugin::call method
See also:
plugin::call
Definition at line 90 of file bolt.php.
static autoloader ($ class) [static]
autoload bolt components
Parameters:
$class class name to load (namespace allowed)
Returns:
void
Definition at line 200 of file bolt.php.
static bolt () [static]
return bolt instance
Returns:
bolt instance
Definition at line 77 of file bolt.php.
static getLoaded () [static]
static return a list of loaded files
Returns:
array of loaded files
Definition at line 190 of file bolt.php.
static init ($ args = array()) [static]
initalize the bolt framework
Parameters:
$args initalization arguments
core: array of core plugins to load
config: array of config params to set
load: array of plugin folders to load. glob is run on each item
Returns:
void
Definition at line 114 of file bolt.php.
static plug () [static]
static method to register a plugin.
passthrough to plugin::plug method
See also:
plugin::plug
Definition at line 100 of file bolt.php.
Member Data Documentation
const DateLongFrm = "l, F jS, Y \n h:i:s A"
Definition at line 245 of file bolt.php.
const DateShortFrm = "F jS, Y \n h:i:s A"
Definition at line 246 of file bolt.php.
const DateTimeOnlyFrm = "l, F jS, Y"
Definition at line 247 of file bolt.php.
const DefaultFilter = FILTER_SANITIZE_STRING
Definition at line 249 of file bolt.php.
const SecondsInDay = 86400
Definition at line 242 of file bolt.php.
const SecondsInHour = 120
Definition at line 241 of file bolt.php.
const SecondsInWeek = 1209600
Definition at line 243 of file bolt.php.
const SecondsInYear = 31536000
Definition at line 244 of file bolt.php.
Referenced by helpers::niceDate().
const TimeOnlyFrm = "h:i:s A"
Definition at line 248 of file bolt.php.
The documentation for this class was generated from the following file:
bolt.php