Bolt: S3 Class Reference
S3 Class Reference
Id
S3.php 43 2008-12-23 14:37:18Z don.schonknecht
Public Member Functions
__construct ($accessKey=null, $secretKey=null, $useSSL=true)
Constructor - if you're not using the class statically.
Static Public Member Functions
static setAuth ($accessKey, $secretKey)
Set AWS access key and secret key.
static listBuckets ($detailed=false)
Get a list of buckets.
static getBucket ($bucket, $prefix=null, $marker=null, $maxKeys=null, $delimiter=null, $returnCommonPrefixes=false)
static putBucket ($bucket, $acl=self::ACL_PRIVATE, $location=false)
Put a bucket.
static deleteBucket ($bucket)
Delete an empty bucket.
static inputFile ($file, $md5sum=true)
Create input info array for putObject().
static inputResource (&$resource, $bufferSize, $md5sum= '')
Create input array info for putObject() with a resource.
static putObject ($input, $bucket, $uri, $acl=self::ACL_PRIVATE, $metaHeaders=array(), $requestHeaders=array())
Put an object.
static putObjectFile ($file, $bucket, $uri, $acl=self::ACL_PRIVATE, $metaHeaders=array(), $contentType=null)
Put an object from a file (legacy function).
static putObjectString ($string, $bucket, $uri, $acl=self::ACL_PRIVATE, $metaHeaders=array(), $contentType= 'text/plain')
Put an object from a string (legacy function).
static getObject ($bucket, $uri, $saveTo=false)
Get an object.
static getObjectInfo ($bucket, $uri, $returnInfo=true)
Get object information.
static copyObject ($srcBucket, $srcUri, $bucket, $uri, $acl=self::ACL_PRIVATE)
Copy an object.
static setBucketLogging ($bucket, $targetBucket, $targetPrefix=null)
Set logging for a bucket.
static getBucketLogging ($bucket)
Get logging status for a bucket.
static disableBucketLogging ($bucket)
Disable bucket logging.
static getBucketLocation ($bucket)
Get a bucket's location.
static setAccessControlPolicy ($bucket, $uri= '', $acp=array())
Set object or bucket Access Control Policy.
static getAccessControlPolicy ($bucket, $uri= '')
Get object or bucket Access Control Policy.
static deleteObject ($bucket, $uri)
Delete an object.
static getAuthenticatedURL ($bucket, $uri, $lifetime, $hostBucket=false, $https=false)
Get a query string authenticated URL.
static createDistribution ($bucket, $enabled=true, $cnames=array(), $comment= '')
Create a CloudFront distribution.
static getDistribution ($distributionId)
Get CloudFront distribution info.
static updateDistribution ($dist)
Update a CloudFront distribution.
static deleteDistribution ($dist)
Delete a CloudFront distribution.
static listDistributions ()
Get a list of CloudFront distributions.
static __getMimeType (&$file)
Get MIME type for file.
static __getSignature ($string)
Generate the auth string: "AWS AccessKey:Signature".
Public Attributes
const ACL_PRIVATE = 'private'
const ACL_PUBLIC_READ = 'public-read'
const ACL_PUBLIC_READ_WRITE = 'public-read-write'
Static Public Attributes
static $useSSL = true
Detailed Description
Id
S3.php 43 2008-12-23 14:37:18Z don.schonknecht
Copyright (c) 2008, Donovan Schšnknecht. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Amazon S3 is a trademark of Amazon.com, Inc. or its affiliates. Amazon S3 PHP class 0.3.9
Definition at line 66 of file external/s3.php.
Constructor & Destructor Documentation
__construct ($ accessKey = null, $ secretKey = null, $ useSSL = true)
Constructor - if you're not using the class statically.
Parameters:
string $accessKey Access key
string $secretKey Secret key
boolean $useSSL Enable SSL
Returns:
void
Definition at line 86 of file external/s3.php.
References $useSSL, and setAuth().
Member Function Documentation
static __getMimeType (&$ file) [static]
Get MIME type for file.
Definition at line 1040 of file external/s3.php.
Referenced by putObject().
static __getSignature ($ string) [static]
Generate the auth string: "AWS AccessKey:Signature".
Definition at line 1088 of file external/s3.php.
Referenced by S3Request::getResponse().
static copyObject ($ srcBucket, $ srcUri, $ bucket, $ uri, $ acl = self::ACL_PRIVATE) [static]
Copy an object.
Parameters:
string $bucket Source bucket name
string $uri Source object URI
string $bucket Destination bucket name
string $uri Destination object URI
constant $acl ACL constant
Returns:
mixed | false
Definition at line 498 of file external/s3.php.
References $uri.
static createDistribution ($ bucket, $ enabled = true, $ cnames = array(), $ comment = '') [static]
Create a CloudFront distribution.
Parameters:
string $bucket Bucket name
boolean $enabled Enabled (true/false)
array $cnames Array containing CNAME aliases
string $comment Use the bucket name as the hostname
Returns:
array | false
Definition at line 800 of file external/s3.php.
References SimpleXMLElement.
static deleteBucket ($ bucket) [static]
Delete an empty bucket.
Parameters:
string $bucket Bucket name
Returns:
boolean
Definition at line 267 of file external/s3.php.
static deleteDistribution ($ dist) [static]
Delete a CloudFront distribution.
Parameters:
array $dist Distribution array info identical to output of getDistribution()
Returns:
boolean
Definition at line 882 of file external/s3.php.
static deleteObject ($ bucket, $ uri) [static]
Delete an object.
Parameters:
string $bucket Bucket name
string $uri Object URI
Returns:
boolean
Definition at line 758 of file external/s3.php.
References $uri.
static disableBucketLogging ($ bucket) [static]
Disable bucket logging.
Parameters:
string $bucket Bucket name
Returns:
boolean
Definition at line 610 of file external/s3.php.
References setBucketLogging().
static getAccessControlPolicy ($ bucket, $ uri = '') [static]
Get object or bucket Access Control Policy.
Parameters:
string $bucket Bucket name
string $uri Object URI
Returns:
mixed | false
Definition at line 702 of file external/s3.php.
References $uri.
static getAuthenticatedURL ($ bucket, $ uri, $ lifetime, $ hostBucket = false, $ https = false) [static]
Get a query string authenticated URL.
Parameters:
string $bucket Bucket name
string $uri Object URI
integer $lifetime Lifetime in seconds
boolean $hostBucket Use the bucket name as the hostname
boolean $https Use HTTPS ($hostBucket should be false for SSL verification)
Returns:
string
Definition at line 782 of file external/s3.php.
References $uri.
static getBucket ($ bucket, $ prefix = null, $ marker = null, $ maxKeys = null, $ delimiter = null, $ returnCommonPrefixes = false) [static]
Definition at line 154 of file external/s3.php.
static getBucketLocation ($ bucket) [static]
Get a bucket's location.
Parameters:
string $bucket Bucket name
Returns:
string | false
Definition at line 621 of file external/s3.php.
static getBucketLogging ($ bucket) [static]
Get logging status for a bucket.
This will return false if logging is not enabled. Note: To enable logging, you also need to grant write access to the log group
Parameters:
string $bucket Bucket name
Returns:
array | false
Definition at line 585 of file external/s3.php.
static getDistribution ($ distributionId) [static]
Get CloudFront distribution info.
Parameters:
string $distributionId Distribution ID from listDistributions()
Returns:
array | false
Definition at line 829 of file external/s3.php.
References SimpleXMLElement.
static getObject ($ bucket, $ uri, $ saveTo = false) [static]
Get an object.
Parameters:
string $bucket Bucket name
string $uri Object URI
mixed $saveTo Filename or resource to write to
Returns:
mixed
Definition at line 439 of file external/s3.php.
References $uri.
static getObjectInfo ($ bucket, $ uri, $ returnInfo = true) [static]
Get object information.
Parameters:
string $bucket Bucket name
string $uri Object URI
boolean $returnInfo Return response information
Returns:
mixed | false
Definition at line 474 of file external/s3.php.
References $uri.
static inputFile ($ file, $ md5sum = true) [static]
Create input info array for putObject().
Parameters:
string $file Input file
mixed $md5sum Use MD5 hash (supply a string if you want to use your own)
Returns:
array | false
Definition at line 288 of file external/s3.php.
static inputResource (&$ resource, $ bufferSize, $ md5sum = '') [static]
Create input array info for putObject() with a resource.
Parameters:
string $resource Input resource to read from
integer $bufferSize Input byte size
string $md5sum MD5 hash to send (optional)
Returns:
array | false
Definition at line 307 of file external/s3.php.
static listBuckets ($ detailed = false) [static]
Get a list of buckets.
Parameters:
boolean $detailed Returns detailed bucket list when true
Returns:
array | false
Definition at line 112 of file external/s3.php.
static listDistributions () [static]
Get a list of CloudFront distributions.
Returns:
array
Definition at line 904 of file external/s3.php.
References SimpleXMLElement.
static putBucket ($ bucket, $ acl = self::ACL_PRIVATE, $ location = false) [static]
Put a bucket.
Parameters:
string $bucket Bucket name
constant $acl ACL flag
string $location Set as "EU" to create buckets hosted in Europe
Returns:
boolean
Definition at line 234 of file external/s3.php.
References DOMDocument.
static putObject ($ input, $ bucket, $ uri, $ acl = self::ACL_PRIVATE, $ metaHeaders = array(), $ requestHeaders = array()) [static]
Put an object.
Parameters:
mixed $input Input data
string $bucket Bucket name
string $uri Object URI
constant $acl ACL constant
array $metaHeaders Array of x-amz-meta-* headers
array $requestHeaders Array of request headers or content type as a string
Returns:
boolean
Definition at line 329 of file external/s3.php.
References $uri, __getMimeType(), and Exception.
Referenced by putObjectFile(), and putObjectString().
static putObjectFile ($ file, $ bucket, $ uri, $ acl = self::ACL_PRIVATE, $ metaHeaders = array(), $ contentType = null) [static]
Put an object from a file (legacy function).
Parameters:
string $file Input file path
string $bucket Bucket name
string $uri Object URI
constant $acl ACL constant
array $metaHeaders Array of x-amz-meta-* headers
string $contentType Content type
Returns:
boolean
Definition at line 409 of file external/s3.php.
References $uri, and putObject().
static putObjectString ($ string, $ bucket, $ uri, $ acl = self::ACL_PRIVATE, $ metaHeaders = array(), $ contentType = 'text/plain') [static]
Put an object from a string (legacy function).
Parameters:
string $string Input data
string $bucket Bucket name
string $uri Object URI
constant $acl ACL constant
array $metaHeaders Array of x-amz-meta-* headers
string $contentType Content type
Returns:
boolean
Definition at line 426 of file external/s3.php.
References $uri, and putObject().
static setAccessControlPolicy ($ bucket, $ uri = '', $ acp = array()) [static]
Set object or bucket Access Control Policy.
Parameters:
string $bucket Bucket name
string $uri Object URI
array $acp Access Control Policy Data (same as the data returned from getAccessControlPolicy)
Returns:
boolean
Definition at line 644 of file external/s3.php.
References $uri, and DOMDocument.
Referenced by setBucketLogging().
static setAuth ($ accessKey, $ secretKey) [static]
Set AWS access key and secret key.
Parameters:
string $accessKey Access key
string $secretKey Secret key
Returns:
void
Definition at line 100 of file external/s3.php.
Referenced by __construct().
static setBucketLogging ($ bucket, $ targetBucket, $ targetPrefix = null) [static]
Set logging for a bucket.
Parameters:
string $bucket Bucket name
string $targetBucket Target bucket (where logs are stored)
string $targetPrefix Log prefix (e,g; domain.com-)
Returns:
boolean
Definition at line 526 of file external/s3.php.
References DOMDocument, and setAccessControlPolicy().
Referenced by disableBucketLogging().
static updateDistribution ($ dist) [static]
Update a CloudFront distribution.
Parameters:
array $dist Distribution array info identical to output of getDistribution()
Returns:
array | false
Definition at line 853 of file external/s3.php.
Member Data Documentation
$useSSL = true [static]
Definition at line 72 of file external/s3.php.
Referenced by __construct(), and S3Request::getResponse().
const ACL_PRIVATE = 'private'
Definition at line 68 of file external/s3.php.
const ACL_PUBLIC_READ = 'public-read'
Definition at line 69 of file external/s3.php.
const ACL_PUBLIC_READ_WRITE = 'public-read-write'
Definition at line 70 of file external/s3.php.
The documentation for this class was generated from the following file:
external/s3.php