Bolt: cookie Class Reference
cookie Class Reference
Public Member Functions
set ($name, $value, $expires=false, $domain=false)
add url params to a url
delete ($name)
get ($name)
getDecodedCookie ($cookie)
Detailed Description
Definition at line 9 of file cookie.php.
Member Function Documentation
delete ($ name)
Definition at line 64 of file cookie.php.
References b::_().
get ($ name)
Definition at line 79 of file cookie.php.
References b::_(), getDecodedCookie(), and p().
getDecodedCookie ($ cookie)
Definition at line 106 of file cookie.php.
Referenced by get().
set ($ name, $ value, $ expires = false, $ domain = false)
add url params to a url
Parameters:
$url base url
$params array of params to add
Returns:
string url with additional params
Definition at line 19 of file cookie.php.
References b::_(), and p().
The documentation for this class was generated from the following file:
cookie.php