Bolt: plugin Class Reference
plugin Class Reference
Public Member Functions
__construct ($fallback=array())
getPlugins ()
setFallbacks ($classes)
getFallbacks ()
__call ($name, $args)
call ($name, $args=array())
call one of our plugins
plug ($name, $class=false)
plugin to bolt
Detailed Description
Definition at line 5 of file plugin.php.
Constructor & Destructor Documentation
__construct ($ fallback = array())
Definition at line 13 of file plugin.php.
References setFallbacks().
Member Function Documentation
__call ($ name, $ args)
Definition at line 36 of file plugin.php.
References call().
call ($ name, $ args = array())
call one of our plugins
Definition at line 43 of file plugin.php.
Referenced by __call(), external::init(), and render::render().
getFallbacks ()
Definition at line 31 of file plugin.php.
getPlugins ()
Definition at line 18 of file plugin.php.
Referenced by render::render().
plug ($ name, $ class = false)
plugin to bolt
Definition at line 146 of file plugin.php.
Referenced by external::init().
setFallbacks ($ classes)
Definition at line 23 of file plugin.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
plugin.php